-- Migration 002: PCGE Accounts (Plan Contable General Empresarial 2019)
-- Standard Chart of Accounts for Peruvian SMEs
-- Reference: https://www.mef.gob.pe/contenidos/contabilidad/pcg2019.php

-- Insert default PCGE accounts (only if they don't exist)
-- Company_id 'default' indicates system-level accounts available to all companies

INSERT OR IGNORE INTO accounts (id, company_id, code, name, type, level) VALUES
-- Class 1: ACTIVO (Assets)
(uuid(), 'default', '10', 'EFECTIVO Y EQUIVALENTES DE EFECTIVO', 'asset', 1),
(uuid(), 'default', '101', 'Caja', 'asset', 2),
(uuid(), 'default', '1011', 'Caja Principal', 'asset', 3),
(uuid(), 'default', '1012', 'Caja Chica', 'asset', 3),
(uuid(), 'default', '102', 'Cuentas Corrientes en Instituciones Financieras', 'asset', 2),
(uuid(), 'default', '1021', 'Cta. Cte. en Moneda Nacional', 'asset', 3),
(uuid(), 'default', '1022', 'Cta. Cte. en Moneda Extranjera', 'asset', 3),
(uuid(), 'default', '104', 'Cuentas por Cobrar a Terceros', 'asset', 2),
(uuid(), 'default', '1041', 'Facturas, Boletas y Otros Comprobantes por Cobrar', 'asset', 3),
(uuid(), 'default', '10411', 'Emitidas en Cartera', 'asset', 4),
(uuid(), 'default', '10412', 'Emitidas en Cobranza', 'asset', 4),
(uuid(), 'default', '12', 'CUENTAS POR COBRAR COMERCIALES - TERCEROS', 'asset', 1),
(uuid(), 'default', '121', 'Facturas, Boletas y Otros Comprobantes por Cobrar', 'asset', 2),
(uuid(), 'default', '1212', 'Emitidas', 'asset', 3),
(uuid(), 'default', '14', 'Cuentas por Cobrar al Personal, a los Accionistas (Socios) y Directores', 'asset', 2),
(uuid(), 'default', '20', 'MERCADERÍAS', 'asset', 1),
(uuid(), 'default', '201', 'Mercaderías', 'asset', 2),
(uuid(), 'default', '2011', 'Mercaderías Almacén', 'asset', 3),
(uuid(), 'default', '20111', 'Costo', 'asset', 4),
(uuid(), 'default', '24', 'Materias Primas', 'asset', 2),
(uuid(), 'default', '25', 'Materiales Auxiliares, Suministros y Repuestos', 'asset', 2),
(uuid(), 'default', '26', 'Envases y Embalajes', 'asset', 2),
(uuid(), 'default', '27', 'Activos Biológicos', 'asset', 2),
(uuid(), 'default', '28', 'Activos Biológicos en Custodia', 'asset', 2),
(uuid(), 'default', '29', 'Desvalorización de Existencias', 'asset', 2),
(uuid(), 'default', '33', 'INMUEBLES, MAQUINARIA Y EQUIPO', 'asset', 1),
(uuid(), 'default', '331', 'Terrenos', 'asset', 2),
(uuid(), 'default', '332', 'Edificaciones', 'asset', 2),
(uuid(), 'default', '333', 'Maquinarias y Equipos de Explotación', 'asset', 2),
(uuid(), 'default', '334', 'Unidades de Transporte', 'asset', 2),
(uuid(), 'default', '335', 'Muebles y Enseres', 'asset', 2),
(uuid(), 'default', '336', 'Equipos de Procesamiento de Información', 'asset', 2),
(uuid(), 'default', '337', 'Software', 'asset', 2),
(uuid(), 'default', '339', 'Obras en Curso', 'asset', 2),
(uuid(), 'default', '34', 'Intangibles', 'asset', 2),
(uuid(), 'default', '35', 'Activos Biológicos en Producción', 'asset', 2),
(uuid(), 'default', '36', 'Desvalorización de Activos Inmovilizados', 'asset', 2),
(uuid(), 'default', '37', 'Activos Diferidos', 'asset', 2),
(uuid(), 'default', '38', 'OTROS ACTIVOS', 'asset', 1),
(uuid(), 'default', '39', 'Depreciación, Amortización y Agotamiento Acumulados', 'asset', 2),

-- Class 2: PASIVO (Liabilities)
(uuid(), 'default', '40', 'TRIBUTOS, CONTRAPRESTACIONES Y APORTES AL SISTEMA DE PENSIONES Y DE SALUD POR PAGAR', 'liability', 1),
(uuid(), 'default', '401', 'Gobierno Central', 'liability', 2),
(uuid(), 'default', '4011', 'IGV', 'liability', 3),
(uuid(), 'default', '40111', 'IGV - Cuenta Propia', 'liability', 4),
(uuid(), 'default', '40112', 'IGV - Terceros', 'liability', 4),
(uuid(), 'default', '4012', 'Impuesto a la Renta', 'liability', 3),
(uuid(), 'default', '402', 'Gobiernos Locales', 'liability', 2),
(uuid(), 'default', '403', 'Impuestos y Contribuciones por pagar', 'liability', 2),
(uuid(), 'default', '404', 'Contribuciones a ESSALUD y ONP', 'liability', 2),
(uuid(), 'default', '41', 'REMUNERACIONES Y PARTICIPACIONES POR PAGAR', 'liability', 1),
(uuid(), 'default', '411', 'Remuneraciones por Pagar', 'liability', 2),
(uuid(), 'default', '412', 'Participaciones por Pagar', 'liability', 2),
(uuid(), 'default', '42', 'CUENTAS POR PAGAR COMERCIALES - TERCEROS', 'liability', 1),
(uuid(), 'default', '421', 'Facturas, Boletas y Otros Comprobantes por Pagar', 'liability', 2),
(uuid(), 'default', '4212', 'Emitidas', 'liability', 3),
(uuid(), 'default', '43', 'CUENTAS POR PAGAR COMERCIALES - RELACIONADAS', 'liability', 1),
(uuid(), 'default', '44', 'CUENTAS POR PAGAR AL PERSONAL, A LOS ACCIONISTAS (SOCIOS) Y DIRECTORES', 'liability', 1),
(uuid(), 'default', '45', 'OBLIGACIONES FINANCIERAS', 'liability', 1),
(uuid(), 'default', '451', 'Préstamos de Instituciones Financieras', 'liability', 2),
(uuid(), 'default', '46', 'CUENTAS POR PAGAR DIVERSAS', 'liability', 1),
(uuid(), 'default', '47', 'BENEFICIOS SOCIALES DE LOS TRABAJADORES', 'liability', 1),
(uuid(), 'default', '48', 'PROVISIONES', 'liability', 1),
(uuid(), 'default', '49', 'PASIVO DIFERIDO', 'liability', 1),

-- Class 3: PATRIMONIO (Equity)
(uuid(), 'default', '50', 'CAPITAL', 'equity', 1),
(uuid(), 'default', '501', 'Capital', 'equity', 2),
(uuid(), 'default', '5011', 'Capital Suscrito y Pagado', 'equity', 3),
(uuid(), 'default', '502', 'Capital Adicional', 'equity', 2),
(uuid(), 'default', '51', 'ACCIONES DE INVERSIÓN', 'equity', 1),
(uuid(), 'default', '52', 'CAPITAL ADICIONAL', 'equity', 1),
(uuid(), 'default', '56', 'RESULTADOS NO REALIZADOS', 'equity', 1),
(uuid(), 'default', '57', 'EXCEDENTE DE REVALUACIÓN', 'equity', 1),
(uuid(), 'default', '58', 'RESERVAS', 'equity', 1),
(uuid(), 'default', '581', 'Reserva Legal', 'equity', 2),
(uuid(), 'default', '582', 'Reservas Voluntarias', 'equity', 2),
(uuid(), 'default', '59', 'RESULTADOS ACUMULADOS', 'equity', 1),
(uuid(), 'default', '591', 'Utilidades no Distribuidas', 'equity', 2),
(uuid(), 'default', '592', 'Pérdidas Acumuladas', 'equity', 2),

-- Class 6: COSTOS (Costs/Expenses)
(uuid(), 'default', '60', 'COMPRAS', 'expense', 1),
(uuid(), 'default', '601', 'Mercaderías', 'expense', 2),
(uuid(), 'default', '6011', 'Mercaderías Almacén', 'expense', 3),
(uuid(), 'default', '6012', 'Mercaderías en Tránsito', 'expense', 3),
(uuid(), 'default', '602', 'Materias Primas', 'expense', 2),
(uuid(), 'default', '603', 'Materiales Auxiliares, Suministros y Repuestos', 'expense', 2),
(uuid(), 'default', '604', 'Envases y Embalajes', 'expense', 2),
(uuid(), 'default', '605', 'Activos Biológicos', 'expense', 2),
(uuid(), 'default', '61', 'Variación de Existencias', 'expense', 2),
(uuid(), 'default', '62', 'GASTOS DE PERSONAL, DIRECTORES Y GERENTES', 'expense', 1),
(uuid(), 'default', '621', 'Remuneraciones', 'expense', 2),
(uuid(), 'default', '6211', 'Sueldos y Salarios', 'expense', 3),
(uuid(), 'default', '6212', 'Salarios en Especie', 'expense', 3),
(uuid(), 'default', '6213', 'Hora Extra', 'expense', 3),
(uuid(), 'default', '622', 'Otras Remuneraciones', 'expense', 2),
(uuid(), 'default', '623', 'Participaciones de los Trabajadores', 'expense', 2),
(uuid(), 'default', '624', 'Contribuciones a ESSALUD y Otros', 'expense', 2),
(uuid(), 'default', '625', 'Seguros', 'expense', 2),
(uuid(), 'default', '63', 'GASTOS DE SERVICIOS PRESTADOS POR TERCEROS', 'expense', 1),
(uuid(), 'default', '631', 'Alquileres', 'expense', 2),
(uuid(), 'default', '6311', 'Alquiler de Oficina', 'expense', 3),
(uuid(), 'default', '6312', 'Alquiler de Local', 'expense', 3),
(uuid(), 'default', '632', 'Mantenimiento y Reparaciones', 'expense', 2),
(uuid(), 'default', '633', 'Gastos de Representación', 'expense', 2),
(uuid(), 'default', '634', 'Gastos de Legalización y Notariales', 'expense', 2),
(uuid(), 'default', '635', 'Gastos de Selección de Personal', 'expense', 2),
(uuid(), 'default', '636', 'Servicios de Terceros', 'expense', 2),
(uuid(), 'default', '637', 'Gastos de Transporte', 'expense', 2),
(uuid(), 'default', '638', 'Gastos de Servicios de Custodia', 'expense', 2),
(uuid(), 'default', '639', 'Otros Servicios', 'expense', 2),
(uuid(), 'default', '64', 'GASTOS POR TRIBUTOS', 'expense', 1),
(uuid(), 'default', '641', 'Tributos', 'expense', 2),
(uuid(), 'default', '642', 'Arbitrios', 'expense', 2),
(uuid(), 'default', '643', 'Licencias y Derechos', 'expense', 2),
(uuid(), 'default', '644', 'Otros Gastos Tributarios', 'expense', 2),
(uuid(), 'default', '65', 'OTROS GASTOS DE GESTIÓN', 'expense', 1),
(uuid(), 'default', '651', 'Gastos de Gestión', 'expense', 2),
(uuid(), 'default', '652', 'Gastos de Investigación y Desarrollo', 'expense', 2),
(uuid(), 'default', '653', 'Gastos de Exploración y Explotación', 'expense', 2),
(uuid(), 'default', '654', 'Gastos de Explotación de Recursos Biológicos', 'expense', 2),
(uuid(), 'default', '655', 'Gastos de Desvalorización de Activos Diferidos', 'expense', 2),
(uuid(), 'default', '656', 'Gastos por Estimación de Cuentas de Cobranza Dudosa', 'expense', 2),
(uuid(), 'default', '657', 'Gastos por Estimación de Valor Neto de Realización de Existencias', 'expense', 2),
(uuid(), 'default', '658', 'Gastos por Estimación de Desvalorización de Activos Inmovilizados', 'expense', 2),
(uuid(), 'default', '659', 'Otros Gastos de Gestión', 'expense', 2),
(uuid(), 'default', '66', 'GASTOS FINANCIEROS', 'expense', 1),
(uuid(), 'default', '661', 'Intereses por Préstamos y Otras Obligaciones', 'expense', 2),
(uuid(), 'default', '662', 'Intereses por Descuentos', 'expense', 2),
(uuid(), 'default', '663', 'Diferencia en Cambio', 'expense', 2),
(uuid(), 'default', '664', 'Diferencia de Cambio - Partidas Monetarias', 'expense', 2),
(uuid(), 'default', '665', 'Otros Gastos Financieros', 'expense', 2),
(uuid(), 'default', '67', 'VALUACIÓN Y DETERIORO DE ACTIVOS Y PROVISIONES', 'expense', 1),
(uuid(), 'default', '671', 'Estimación de Cuentas de Cobranza Dudosa', 'expense', 2),
(uuid(), 'default', '672', 'Desvalorización de Existencias', 'expense', 2),
(uuid(), 'default', '673', 'Desvalorización de Activos Inmovilizados', 'expense', 2),
(uuid(), 'default', '674', 'Desvalorización de Activos Intangibles', 'expense', 2),
(uuid(), 'default', '675', 'Pérdida por Deterioro de Activos Biológicos', 'expense', 2),
(uuid(), 'default', '676', 'Provisiones', 'expense', 2),
(uuid(), 'default', '68', 'COSTO DE VENTAS', 'expense', 1),
(uuid(), 'default', '681', 'Mercaderías', 'expense', 2),
(uuid(), 'default', '6811', 'Mercaderías Almacén', 'expense', 3),
(uuid(), 'default', '682', 'Productos Terminados', 'expense', 2),
(uuid(), 'default', '683', 'Productos en Proceso', 'expense', 2),
(uuid(), 'default', '684', 'Servicios', 'expense', 2),
(uuid(), 'default', '685', 'Materias Primas', 'expense', 2),
(uuid(), 'default', '686', 'Materias Auxiliares, Suministros y Repuestos', 'expense', 2),
(uuid(), 'default', '687', 'Envases y Embalajes', 'expense', 2),
(uuid(), 'default', '688', 'Activos Biológicos', 'expense', 2),
(uuid(), 'default', '689', 'Otros Costos', 'expense', 2),
(uuid(), 'default', '69', 'COSTO DE VENTAS', 'expense', 1),
(uuid(), 'default', '691', 'Mercaderías', 'expense', 2),
(uuid(), 'default', '6911', 'Mercaderías Almacén', 'expense', 3),

-- Class 7: INCOME (Revenue)
(uuid(), 'default', '70', 'VENTAS', 'income', 1),
(uuid(), 'default', '701', 'Mercaderías', 'income', 2),
(uuid(), 'default', '7011', 'Mercaderías Almacén', 'income', 3),
(uuid(), 'default', '702', 'Productos Terminados', 'income', 2),
(uuid(), 'default', '703', 'Productos en Proceso', 'income', 2),
(uuid(), 'default', '704', 'Servicios', 'income', 2),
(uuid(), 'default', '705', 'Ingresos de Actividades Afines', 'income', 2),
(uuid(), 'default', '71', 'PRODUCCIÓN ALMACENADA (Variación de Productos en Proceso)', 'income', 2),
(uuid(), 'default', '711', 'Variación de Productos en Proceso', 'income', 3),
(uuid(), 'default', '72', 'PRODUCCIÓN INMOVILIZADA', 'income', 2),
(uuid(), 'default', '721', 'Producción Inmovilizada - Intangibles', 'income', 3),
(uuid(), 'default', '73', 'DESCUENTOS, REBAJAS Y BONIFICACIONES OBTENIDOS', 'income', 1),
(uuid(), 'default', '731', 'Descuentos, Rebajas y Bonificaciones Obtelidos', 'income', 2),
(uuid(), 'default', '74', 'DESCUENTOS, REBAJAS Y BONIFICACIONES CONCEDIDOS', 'income', 2),
(uuid(), 'default', '741', 'Descuentos, Rebajas y Bonificaciones Concedidos', 'income', 3),
(uuid(), 'default', '75', 'OTROS INGRESOS DE GESTIÓN', 'income', 1),
(uuid(), 'default', '751', 'Comisiones y Honorarios', 'income', 2),
(uuid(), 'default', '752', 'Regalías', 'income', 2),
(uuid(), 'default', '753', 'Dividendos', 'income', 2),
(uuid(), 'default', '754', 'Arrendamientos', 'income', 2),
(uuid(), 'default', '755', 'Ingresos por Formas Associativas', 'income', 2),
(uuid(), 'default', '756', 'Enajenación de Activos Inmovilizados', 'income', 2),
(uuid(), 'default', '757', 'Ingresos Extraordinarios', 'income', 2),
(uuid(), 'default', '758', 'Ingresos por Derivados', 'income', 2),
(uuid(), 'default', '759', 'Otros Ingresos de Gestión', 'income', 2),
(uuid(), 'default', '76', 'INGRESOS FINANCIEROS', 'income', 1),
(uuid(), 'default', '761', 'Intereses por Préstamos Otorgados', 'income', 2),
(uuid(), 'default', '762', 'Intereses por Depósitos', 'income', 2),
(uuid(), 'default', '763', 'Diferencia en Cambio', 'income', 2),
(uuid(), 'default', '764', 'Diferencia de Cambio - Partidas Monetarias', 'income', 2),
(uuid(), 'default', '765', 'Otros Ingresos Financieros', 'income', 2),
(uuid(), 'default', '77', 'INGRESOS EXCEPCIONALES', 'income', 1),
(uuid(), 'default', '771', 'Ingresos por Excedentes de Inventarios', 'income', 2),
(uuid(), 'default', '772', 'Ingresos por Reevaluación de Activos', 'income', 2),
(uuid(), 'default', '773', 'Ingresos por Bonificaciones Recibidas', 'income', 2),
(uuid(), 'default', '774', 'Otros Ingresos Excepcionales', 'income', 2),
(uuid(), 'default', '78', 'CARGAS CUBIERTAS POR PROVISIONES DEL EJERCICIO', 'income', 1),
(uuid(), 'default', '781', 'Cargas Cubiertas por Provisiones del Ejercicio', 'income', 2);

-- Note: This migration assumes UUID() function is available
-- For SQLite, you can use the uuid extension or generate UUIDs in application code
